// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterFormats/Lerc2Codec",[],function(){var z={unstuff:function(a,b,f,c,d,k,h,n){var e=(1<<f)-1,m=0,p,g=0,l,q;a[a.length-1]<<=8*(4*a.length-Math.ceil(f*c/8));if(d)for(p=0;p<c;p++)0===g&&(q=a[m++],g=32),g>=f?(l=q>>>g-f&e,g-=f):(g=f-g,l=(q&e)<<g&e,q=a[m++],g=32-g,l+=q>>>g),b[p]=d[l];else for(d=Math.ceil((n-k)/h),p=0;p<c;p++)0===g&&(q=a[m++],g=32),g>=f?(l=q>>>g-f&e,g-=f):(g=f-g,l=(q&e)<<g&e,q=a[m++],g=32-g,l+=q>>>g),b[p]=l<d?k+l*h:n},unstuffLUT:function(a,b,f,c,d,k){var h=(1<<b)-
1,n=0,e=0,m=0,p=m=0,g,l=[];a[a.length-1]<<=8*(4*a.length-Math.ceil(b*f/8));for(var q=Math.ceil((k-c)/d),e=0;e<f;e++)0===m&&(g=a[n++],m=32),m>=b?(p=g>>>m-b&h,m-=b):(m=b-m,p=(g&h)<<m&h,g=a[n++],m=32-m,p+=g>>>m),l[e]=p<q?c+p*d:k;l.unshift(c);return l},unstuff2:function(a,b,f,c,d,k,h,n){var e=(1<<f)-1,m=0,p,g=0,l=0,q,t,r;if(d)for(p=0;p<c;p++)0===g&&(t=a[m++],g=32,l=0),g>=f?(q=t>>>l&e,g-=f,l+=f):(r=f-g,q=t>>>l&e,t=a[m++],g=32-r,q|=(t&(1<<r)-1)<<f-r,l=r),b[p]=d[q];else for(d=Math.ceil((n-k)/h),p=0;p<c;p++)0===
g&&(t=a[m++],g=32,l=0),g>=f?(q=t>>>l&e,g-=f,l+=f):(r=f-g,q=t>>>l&e,t=a[m++],g=32-r,q|=(t&(1<<r)-1)<<f-r,l=r),b[p]=q<d?k+q*h:n;return b},unstuffLUT2:function(a,b,f,c,d,k){for(var h=(1<<b)-1,n=0,e=0,m=0,p=0,g=0,l=0,q,t=[],r=Math.ceil((k-c)/d),e=0;e<f;e++)0===p&&(q=a[n++],p=32,l=0),p>=b?(g=q>>>l&h,p-=b,l+=b):(m=b-p,g=q>>>l&h,q=a[n++],p=32-m,g|=(q&(1<<m)-1)<<b-m,l=m),t[e]=g<r?c+g*d:k;t.unshift(c);return t},originalUnstuff:function(a,b,f,c){var d=(1<<f)-1,k=0,h,n=0,e,m;a[a.length-1]<<=8*(4*a.length-Math.ceil(f*
c/8));for(h=0;h<c;h++)0===n&&(m=a[k++],n=32),n>=f?(e=m>>>n-f&d,n-=f):(n=f-n,e=(m&d)<<n&d,m=a[k++],n=32-n,e+=m>>>n),b[h]=e;return b},originalUnstuff2:function(a,b,f,c){var d=(1<<f)-1,k=0,h,n=0,e=0,m,p,g;for(h=0;h<c;h++)0===n&&(p=a[k++],n=32,e=0),n>=f?(m=p>>>e&d,n-=f,e+=f):(g=f-n,m=p>>>e&d,p=a[k++],n=32-g,m|=(p&(1<<g)-1)<<f-g,e=g),b[h]=m;return b}},v={HUFFMAN_LUT_BITS_MAX:12,computeChecksumFletcher32:function(a){for(var b=65535,f=65535,c=a.length,d=Math.floor(c/2),k=0;d;){var h=359<=d?359:d,d=d-h;do b+=
a[k++]<<8,f+=b+=a[k++];while(--h);b=(b&65535)+(b>>>16);f=(f&65535)+(f>>>16)}c&1&&(f+=b+=a[k]<<8);return((f&65535)+(f>>>16)<<16|(b&65535)+(b>>>16))>>>0},readHeaderInfo:function(a,b){var f=b.ptr,c=new Uint8Array(a,f,6),d={};d.fileIdentifierString=String.fromCharCode.apply(null,c);if(0!==d.fileIdentifierString.lastIndexOf("Lerc2",0))throw"Unexpected file identifier string (expect Lerc2 ): "+d.fileIdentifierString;var f=f+6,c=new DataView(a,f,8),k=c.getInt32(0,!0);d.fileVersion=k;f+=4;3<=k&&(d.checksum=
c.getUint32(4,!0),f+=4);c=new DataView(a,f,12);d.height=c.getUint32(0,!0);d.width=c.getUint32(4,!0);f+=8;4<=k?(d.numDims=c.getUint32(8,!0),f+=4):d.numDims=1;c=new DataView(a,f,40);d.numValidPixel=c.getUint32(0,!0);d.microBlockSize=c.getInt32(4,!0);d.blobSize=c.getInt32(8,!0);d.imageType=c.getInt32(12,!0);d.maxZError=c.getFloat64(16,!0);d.zMin=c.getFloat64(24,!0);d.zMax=c.getFloat64(32,!0);f+=40;b.headerInfo=d;b.ptr=f;if(3<=k&&(a=this.computeChecksumFletcher32(new Uint8Array(a,f-(4<=k?52:48),d.blobSize-
14)),a!==d.checksum))throw"Checksum failed.";return!0},checkMinMaxRanges:function(a,b){var f=b.headerInfo,c=this.getDataTypeArray(f.imageType),d=f.numDims*this.getDataTypeSize(f.imageType),k=this.readSubArray(a,b.ptr,c,d);a=this.readSubArray(a,b.ptr+d,c,d);b.ptr+=2*d;d=!0;for(b=0;b<f.numDims;b++)if(k[b]!==a[b]){d=!1;break}f.minValues=k;f.maxValues=a;return d},readSubArray:function(a,b,f,c){if(f===Uint8Array)a=new Uint8Array(a,b,c);else{var d=new ArrayBuffer(c);(new Uint8Array(d)).set(new Uint8Array(a,
b,c));a=new f(d)}return a},readMask:function(a,b){var f=b.ptr,c=b.headerInfo,d=c.width*c.height,k=c.numValidPixel,h=new DataView(a,f,4),c={};c.numBytes=h.getUint32(0,!0);f+=4;if((0===k||d===k)&&0!==c.numBytes)throw"invalid mask";if(0===k)k=new Uint8Array(Math.ceil(d/8)),c.bitset=k,h=new Uint8Array(d),b.pixels.resultMask=h,f+=c.numBytes;else if(0<c.numBytes){k=new Uint8Array(Math.ceil(d/8));h=new DataView(a,f,c.numBytes);a=h.getInt16(0,!0);var n=2,e=0,m=0;do{if(0<a)for(;a--;)k[e++]=h.getUint8(n++);
else for(m=h.getUint8(n++),a=-a;a--;)k[e++]=m;a=h.getInt16(n,!0);n+=2}while(n<c.numBytes);if(-32768!==a||e<k.length)throw"Unexpected end of mask RLE encoding";h=new Uint8Array(d);for(n=n=a=0;n<d;n++)n&7?(a=k[n>>3],a<<=n&7):a=k[n>>3],a&128&&(h[n]=1);b.pixels.resultMask=h;c.bitset=k;f+=c.numBytes}b.ptr=f;b.mask=c;return!0},readDataOneSweep:function(a,b,f){var c=b.ptr,d=b.headerInfo,k=d.numDims,h=d.width*d.height,d=d.numValidPixel*v.getDataTypeSize(d.imageType)*k,n=b.pixels.resultMask;if(f===Uint8Array)a=
new Uint8Array(a,c,d);else{var e=new ArrayBuffer(d);(new Uint8Array(e)).set(new Uint8Array(a,c,d));a=new f(e)}if(a.length===h*k)b.pixels.resultPixels=a;else{b.pixels.resultPixels=new f(h*k);var m=e=f=0,p=0;if(1<k)for(m=0;m<k;m++)for(p=m*h,e=0;e<h;e++)n[e]&&(b.pixels.resultPixels[p+e]=a[f++]);else for(e=0;e<h;e++)n[e]&&(b.pixels.resultPixels[e]=a[f++])}b.ptr=c+d;return!0},readHuffmanTree:function(a,b){var f=this.HUFFMAN_LUT_BITS_MAX,c=new DataView(a,b.ptr,16);b.ptr+=16;if(2>c.getInt32(0,!0))throw"unsupported Huffman version";
var d=c.getInt32(4,!0),k=c.getInt32(8,!0),c=c.getInt32(12,!0);if(k>=c)return!1;var h=new Uint32Array(c-k);v.decodeBits(a,b,h);var n=[],e,m,p;for(e=k;e<c;e++)m=e-(e<d?0:d),n[m]={first:h[e-k],second:null};e=a.byteLength-b.ptr;h=new ArrayBuffer(4*Math.ceil(e/4));(new Uint8Array(h)).set(new Uint8Array(a,b.ptr,e));a=new Uint32Array(h);b=0;var g,h=0;g=a[0];for(e=k;e<c;e++)m=e-(e<d?0:d),p=n[m].first,0<p&&(n[m].second=g<<b>>>32-p,32-b>=p?(b+=p,32===b&&(b=0,h++,g=a[h])):(b+=p-32,h++,g=a[h],n[m].second|=g>>>
32-b));var l=g=0,q=new H;for(e=0;e<n.length;e++)void 0!==n[e]&&(g=Math.max(g,n[e].first));l=g>=f?f:g;30<=g&&console.log("WARning, large NUM LUT BITS IS "+g);var f=[],t,r;for(e=k;e<c;e++)if(m=e-(e<d?0:d),p=n[m].first,0<p)if(k=[p,m],p<=l)for(m=n[m].second<<l-p,t=1<<l-p,p=0;p<t;p++)f[m|p]=k;else for(m=n[m].second,t=q,--p;0<=p;p--)(r=m>>>p&1)?(t.right||(t.right=new H),t=t.right):(t.left||(t.left=new H),t=t.left),0!==p||t.val||(t.val=k[1]);return{decodeLut:f,numBitsLUTQick:l,numBitsLUT:g,tree:q,stuffedData:a,
srcPtr:h,bitPos:b}},readHuffman:function(a,b,f){var c=b.headerInfo,d=c.numDims,k=b.headerInfo.height,h=b.headerInfo.width,n=h*k,e=this.readHuffmanTree(a,b);a=e.decodeLut;var m=e.tree,p=e.stuffedData,g=e.srcPtr,l=e.bitPos,q=e.numBitsLUTQick,e=e.numBitsLUT,t=0===b.headerInfo.imageType?128:0,r,w,u=b.pixels.resultMask,v,z,x,A,y,C,E=0;0<l&&(g++,l=0);var F=p[g],G=1===b.encodeMode,D=new f(n*d),B=D,I;for(I=0;I<c.numDims;I++){1<d&&(B=new f(D.buffer,n*I,n),E=0);if(b.headerInfo.numValidPixel===h*k)for(x=y=0;x<
k;x++)for(A=0;A<h;A++,y++){w=0;r=v=F<<l>>>32-q;32-l<q&&(r=v|=p[g+1]>>>64-l-q);if(a[r])w=a[r][1],l+=a[r][0];else for(r=v=F<<l>>>32-e,32-l<e&&(r=v|=p[g+1]>>>64-l-e),r=m,C=0;C<e;C++)if(r=(z=v>>>e-C-1&1)?r.right:r.left,!r.left&&!r.right){w=r.val;l=l+C+1;break}32<=l&&(l-=32,g++,F=p[g]);w-=t;G?(w=0<A?w+E:0<x?w+B[y-h]:w+E,w&=255,E=B[y]=w):B[y]=w}else for(x=y=0;x<k;x++)for(A=0;A<h;A++,y++)if(u[y]){w=0;r=v=F<<l>>>32-q;32-l<q&&(r=v|=p[g+1]>>>64-l-q);if(a[r])w=a[r][1],l+=a[r][0];else for(r=v=F<<l>>>32-e,32-
l<e&&(r=v|=p[g+1]>>>64-l-e),r=m,C=0;C<e;C++)if(r=(z=v>>>e-C-1&1)?r.right:r.left,!r.left&&!r.right){w=r.val;l=l+C+1;break}32<=l&&(l-=32,g++,F=p[g]);w-=t;G?(w=0<A&&u[y-1]?w+E:0<x&&u[y-h]?w+B[y-h]:w+E,w&=255,E=B[y]=w):B[y]=w}b.ptr=b.ptr+4*(g+1)+(0<l?4:0)}b.pixels.resultPixels=D},decodeBits:function(a,b,f,c,d){var k=b.headerInfo,h=k.fileVersion,n=0,e=new DataView(a,b.ptr,5),m=e.getUint8(0);n++;var p=m>>6,g=0===p?4:3-p,l=0<(m&32)?!0:!1,p=m&31,m=0;if(1===g)m=e.getUint8(n),n++;else if(2===g)m=e.getUint16(n,
!0),n+=2;else if(4===g)m=e.getUint32(n,!0),n+=4;else throw"Invalid valid pixel count type";var g=2*k.maxZError,q,t;d=1<k.numDims?k.maxValues[d]:k.zMax;if(l){b.counter.lut++;l=e.getUint8(n);n++;k=Math.ceil((l-1)*p/8);q=Math.ceil(k/4);q=new ArrayBuffer(4*q);t=new Uint8Array(q);b.ptr+=n;t.set(new Uint8Array(a,b.ptr,k));n=new Uint32Array(q);b.ptr+=k;for(e=0;l-1>>>e;)e++;k=Math.ceil(m*e/8);q=Math.ceil(k/4);q=new ArrayBuffer(4*q);t=new Uint8Array(q);t.set(new Uint8Array(a,b.ptr,k));a=new Uint32Array(q);
b.ptr+=k;b=3<=h?z.unstuffLUT2(n,p,l-1,c,g,d):z.unstuffLUT(n,p,l-1,c,g,d);3<=h?z.unstuff2(a,f,e,m,b):z.unstuff(a,f,e,m,b)}else b.counter.bitstuffer++,e=p,b.ptr+=n,0<e&&(k=Math.ceil(m*e/8),q=Math.ceil(k/4),q=new ArrayBuffer(4*q),t=new Uint8Array(q),t.set(new Uint8Array(a,b.ptr,k)),a=new Uint32Array(q),b.ptr+=k,3<=h?null==c?z.originalUnstuff2(a,f,e,m):z.unstuff2(a,f,e,m,!1,c,g,d):null==c?z.originalUnstuff(a,f,e,m):z.unstuff(a,f,e,m,!1,c,g,d))},readTiles:function(a,b,f){var c=b.headerInfo,d=c.width,k=
c.height,h=c.microBlockSize,n=c.imageType,e=v.getDataTypeSize(n),m=Math.ceil(d/h),p=Math.ceil(k/h);b.pixels.numBlocksY=p;b.pixels.numBlocksX=m;for(var g=b.pixels.ptr=0,l=0,q=0,t=0,r=0,w=0,u=0,z=0,H=g=0,x=0,A=0,u=u=g=u=0,y,C=new f(h*h),E=k%h||h,F=d%h||h,c=c.numDims,G,D=b.pixels.resultMask,B=b.pixels.resultPixels,q=0;q<p;q++)for(r=q!==p-1?h:E,t=0;t<m;t++)for(w=t!==m-1?h:F,x=q*d*h+t*h,A=d-w,G=0;G<c;G++){1<c&&(B=new f(b.pixels.resultPixels.buffer,d*k*G*e,d*k));u=a.byteLength-b.ptr;l=new DataView(a,b.ptr,
Math.min(10,u));y={};u=0;z=l.getUint8(0);u++;g=z>>6&255;H=z>>2&15;if(H!==(t*h>>3&15))throw"integrity issue";z&=3;if(3<z)throw b.ptr+=u,"Invalid block encoding ("+z+")";if(2===z)b.counter.constant++,b.ptr+=u;else if(0===z){b.counter.uncompressed++;b.ptr+=u;u=r*w*e;g=a.byteLength-b.ptr;u=u<g?u:g;g=new ArrayBuffer(0===u%e?u:u+e-u%e);l=new Uint8Array(g);l.set(new Uint8Array(a,b.ptr,u));y=new f(g);u=0;if(D)for(g=0;g<r;g++){for(l=0;l<w;l++)D[x]&&(B[x]=y[u++]),x++;x+=A}else for(g=0;g<r;g++){for(l=0;l<w;l++)B[x++]=
y[u++];x+=A}b.ptr+=u*e}else if(g=v.getDataTypeUsed(n,g),y=v.getOnePixel(y,u,g,l),u+=v.getDataTypeSize(g),3===z)if(b.ptr+=u,b.counter.constantoffset++,D)for(g=0;g<r;g++){for(l=0;l<w;l++)D[x]&&(B[x]=y),x++;x+=A}else for(g=0;g<r;g++){for(l=0;l<w;l++)B[x++]=y;x+=A}else if(b.ptr+=u,v.decodeBits(a,b,C,y,G),u=0,D)for(g=0;g<r;g++){for(l=0;l<w;l++)D[x]&&(B[x]=C[u++]),x++;x+=A}else for(g=0;g<r;g++){for(l=0;l<w;l++)B[x++]=C[u++];x+=A}}},formatFileInfo:function(a){return{fileIdentifierString:a.headerInfo.fileIdentifierString,
fileVersion:a.headerInfo.fileVersion,imageType:a.headerInfo.imageType,height:a.headerInfo.height,width:a.headerInfo.width,numValidPixel:a.headerInfo.numValidPixel,microBlockSize:a.headerInfo.microBlockSize,blobSize:a.headerInfo.blobSize,maxZError:a.headerInfo.maxZError,pixelType:v.getPixelType(a.headerInfo.imageType),eofOffset:a.eofOffset,mask:a.mask?{numBytes:a.mask.numBytes}:null,pixels:{numBlocksX:a.pixels.numBlocksX,numBlocksY:a.pixels.numBlocksY,maxValue:a.headerInfo.zMax,minValue:a.headerInfo.zMin,
noDataValue:a.noDataValue}}},constructConstantSurface:function(a){var b=a.headerInfo.zMax,f=a.headerInfo.numDims,c=a.headerInfo.height*a.headerInfo.width,d=c*f,k=0,h=0,n=0,e=a.pixels.resultMask;if(e)if(1<f)for(k=0;k<f;k++)for(n=k*c,h=0;h<c;h++)e[h]&&(a.pixels.resultPixels[n+h]=b);else for(h=0;h<c;h++)e[h]&&(a.pixels.resultPixels[h]=b);else if(a.pixels.resultPixels.fill)a.pixels.resultPixels.fill(b);else for(h=0;h<d;h++)a.pixels.resultPixels[h]=b},getDataTypeArray:function(a){switch(a){case 0:a=Int8Array;
break;case 1:a=Uint8Array;break;case 2:a=Int16Array;break;case 3:a=Uint16Array;break;case 4:a=Int32Array;break;case 5:a=Uint32Array;break;case 6:a=Float32Array;break;case 7:a=Float64Array;break;default:a=Float32Array}return a},getPixelType:function(a){switch(a){case 0:a="S8";break;case 1:a="U8";break;case 2:a="S16";break;case 3:a="U16";break;case 4:a="S32";break;case 5:a="U32";break;case 6:a="F32";break;case 7:a="F64";break;default:a="F32"}return a},isValidPixelValue:function(a,b){if(null==b)return!1;
switch(a){case 0:a=-128<=b&&127>=b;break;case 1:a=0<=b&&255>=b;break;case 2:a=-32768<=b&&32767>=b;break;case 3:a=0<=b&&65536>=b;break;case 4:a=-2147483648<=b&&2147483647>=b;break;case 5:a=0<=b&&4294967296>=b;break;case 6:a=-3.4027999387901484E38<=b&&3.4027999387901484E38>=b;break;case 7:a=4.9E-324<=b&&1.7976931348623157E308>=b;break;default:a=!1}return a},getDataTypeSize:function(a){var b=0;switch(a){case 0:case 1:b=1;break;case 2:case 3:b=2;break;case 4:case 5:case 6:b=4;break;case 7:b=8;break;default:b=
a}return b},getDataTypeUsed:function(a,b){var f=a;switch(a){case 2:case 4:f=a-b;break;case 3:case 5:f=a-2*b;break;case 6:f=0===b?a:1===b?2:1;break;case 7:f=0===b?a:a-2*b+1;break;default:f=a}return f},getOnePixel:function(a,b,f,c){a=0;switch(f){case 0:a=c.getInt8(b);break;case 1:a=c.getUint8(b);break;case 2:a=c.getInt16(b,!0);break;case 3:a=c.getUint16(b,!0);break;case 4:a=c.getInt32(b,!0);break;case 5:a=c.getUInt32(b,!0);break;case 6:a=c.getFloat32(b,!0);break;case 7:a=c.getFloat64(b,!0);break;default:throw"the decoder does not understand this pixel type";
}return a}},H=function(a,b,f){this.val=a;this.left=b;this.right=f};return{decode:function(a,b){b=b||{};var f=b.noDataValue,c=0,d={};d.ptr=b.inputOffset||0;d.pixels={};if(v.readHeaderInfo(a,d)){var c=d.headerInfo,k=c.fileVersion,h=v.getDataTypeArray(c.imageType);v.readMask(a,d);c.numValidPixel===c.width*c.height||d.pixels.resultMask||(d.pixels.resultMask=b.maskData);var n=c.width*c.height;d.pixels.resultPixels=new h(n*c.numDims);d.counter={onesweep:0,uncompressed:0,lut:0,bitstuffer:0,constant:0,constantoffset:0};
if(0!==c.numValidPixel)if(c.zMax===c.zMin)v.constructConstantSurface(d);else if(4<=k&&v.checkMinMaxRanges(a,d))v.constructConstantSurface(d);else{var e=new DataView(a,d.ptr,2),m=e.getUint8(0);d.ptr++;if(m)v.readDataOneSweep(a,d,h);else if(1<k&&1>=c.imageType&&1E-5>Math.abs(c.maxZError-.5)){e=e.getUint8(1);d.ptr++;d.encodeMode=e;if(2<e||4>k&&1<e)throw"Invalid Huffman flag "+e;e?v.readHuffman(a,d,h):v.readTiles(a,d,h)}else v.readTiles(a,d,h)}d.eofOffset=d.ptr;b.inputOffset?(a=d.headerInfo.blobSize+
b.inputOffset-d.ptr,1<=Math.abs(a)&&(d.eofOffset=b.inputOffset+d.headerInfo.blobSize)):(a=d.headerInfo.blobSize-d.ptr,1<=Math.abs(a)&&(d.eofOffset=d.headerInfo.blobSize));a={width:c.width,height:c.height,pixelData:d.pixels.resultPixels,minValue:c.zMin,maxValue:c.zMax,validPixelCount:c.numValidPixel,dimCount:c.numDims,dimStats:{minValues:c.minValues,maxValues:c.maxValues},maskData:d.pixels.resultMask};if(d.pixels.resultMask&&v.isValidPixelValue(c.imageType,f)){k=d.pixels.resultMask;for(c=0;c<n;c++)k[c]||
(a.pixelData[c]=f);a.noDataValue=f}d.noDataValue=f;b.returnFileInfo&&(a.fileInfo=v.formatFileInfo(d));return a}},getBandCount:function(a){for(var b=0,f=0,c={ptr:0,pixels:{}};f<a.byteLength-58;)v.readHeaderInfo(a,c),f+=c.headerInfo.blobSize,b++,c.ptr=f;return b}}});